### PR TITLE
Readme overhaul

### PR DESCRIPTION
**Pull request by mulcmu**
I started to update the installation steps based on your configuration video and ended up with a lot of changes.

### CODE REVIEW

**Comment by mulcmu** [comment]
Ready for your review.  2nd commit corrected link that pointed back to my fork for testing.

**Comment by Thomas55555** [comment]
I can't see any changes. Please check your commit.

**Comment by Thomas55555** [comment]
No

**Comment by Thomas55555** [comment]
Did you see my review actually? I think I have just finished it, so you weren't be able to see my change requests?

**Comment by mulcmu** [comment]
I did not see you review comments before the squash.

**Comment by Thomas55555** [comment]
> I did not see you review comments before the squash.

I just suggested to remove the supported models. People could be irritated, if they see some models without the `X`.

**Comment by mulcmu** [comment]
I remove the list of models.  Still says:

> Husqvarna Automowers with built-in *Automower® Connect* or with the *Automower® Connect Module* are supported.

**Comment by Thomas55555** [comment]
Thx

**Pull request merged**
