### PR TITLE
Add human friendly status

### PR DESCRIPTION
**Pull request by simontegelid**
As discussed in https://github.com/Thomas55555/husqvarna_automower/discussions/91#discussion-3534417

Adds a human readable `status` (not to be confused with `state`)

Makes the vacuum card look like this (compare to the screenshot in the discussion above)
image

### CODE REVIEW

**Comment by simontegelid** [comment]
Hm, I see that I missed a few quotes in the ERROR state line. Don't merge just yet...

**Comment by simontegelid** [comment]
Now it looks as it should
Screenshot_20210823-172754_Home_Assistant

**Comment by Thomas55555** [comment]
You think, that's okay?

**Comment by simontegelid** [comment]
Nice additions, but why are you assigning everything from the coordinator to the HusqvarnaVacuumEntity instance as members instead of just putting stuff on the stack while fiddling in the methods? I did clean all of that in my fork if you want to take a look. All in all, I think this can be merged.

**Comment by Thomas55555** [comment]
It's because of my programming skills. I just do, what is working, and then I'm happy :)
I'm sorry, but I'm not sure, where I can see this stuff, in your fork. I'm always happy for new ideas.

**Comment by Thomas55555** [comment]
Ah, okay, it's in the master branch. I'll have a look at it.

**Comment by simontegelid** [comment]
I see ☺️ Anyways, I think this PR can be merged. I will send a few more PRs in the coming days, I've had some more issues as you saw in my fork. Thanks for a great job!

**Comment by Thomas55555** [comment]
Okay. Thank you, for your help.

**Comment by simontegelid** [comment]
Beautiful! 

image

**Comment by ripvega** [comment]
How do I get the above card? The only vacuum card I'm finding in HA is the Mushroom card.

**Comment by simontegelid** [comment]
> How do I get the above card? The only vacuum card I'm finding in HA is the Mushroom card.

I have a tailored version of https://github.com/denysdovhan/vacuum-card

**Comment by ripvega** [comment]
Thank you. Would you care to share your card config to get me started?

**Pull request merged**
