### PR TITLE
fix update not working

### LINKED ISSUE #135: Headlight mode is not updating
I've noticed, that the new feature for setting the headlight mode is only updating, after a HA restart. Same for the Android Automower App: I have to restart it, to see the changes in the headlight mode. Right now, not sure, why it is like that.

### PR DESCRIPTION
**Pull request by Thomas55555**
Fixes #135 
What do you think about it?

### CODE REVIEW

**Comment by simontegelid** [comment]
So the headlight response is wrapped in some other way than the rest of the websocket events? Should be handled in aioautomower in that case, so that it is invisible from this integration. I havent seen the responses myself, so hard to tell exactly how it should be done. I would recommend doing an update in aioautomower.session._update_data to pack the headlight similar to how it is structured in the REST response.

**Comment by Thomas55555** [comment]
Yes. Have you seen this? https://github.com/Thomas55555/husqvarna_automower/issues/135#issuecomment-964350369
There you can see, how it is wrapped.

**Comment by Thomas55555** [comment]
Now huqvarna replied to my email. As I am now in contact with them, I asked them, if they want to change their websocket json-string, so we don't have to change the wrapping.

**Comment by Thomas55555** [comment]
Husqvarna said, they will bring that to the developers. I hope they change it. But right now, it wouldn't update anyway, because the `_attr_current_option` is only in the init part. So I think with the property it's working. I suggest to merge it, as a quick fix and we correct it, when husqvarna decided, if they change it or not.

**Pull request merged**
