### PR TITLE
Extend support for translations

### PR DESCRIPTION
**Pull request by astrandb**
### Support for entity name translation is introduced. 

All entity platforms are supported and there are no breaking changes.
Note that the language for entity name translation is selected globally in HA, Goto Settings->System->General and select language and restart HA. Currently only English and Swedish are supported. Other languages will default to English names. The language of sensor states are controlled by the language setting in your personal profile.

#### Known limitations:
- Some of the strings in the vacuum entity dialog are handled by frontend and there is no support in HA for frontend localization from custom components.
- Dynamic messages e.g. "Schedule, next start Fri 10:00" can not be translated until HA core supports placeholders in this context.

#### Further development in separate PR:s
- Add translation of error status messages - Perhaps not necessary, can be a lot of work to maintain in all languages. One alternative is to "move" all error strings from const.py to en.json and it will be up to the translators to implement in their language when they have the energy.
- Fix other supported language files to simplify for translators. Can wait until the first two languages are verified. @Thomas55555 - What is your native language?

All comments are welcome.

### CODE REVIEW

**Comment by Thomas55555** [comment]
grafik
My native language is german. But I prefer HA in english, because some translations are really not understandable.
For testing I selected `Svenska` as language. Opend it in a incognito browser, so it's not influenced by any cached values and i got the result above.
It seems, that the states are translated, but not the names. Have you tested it?

**Comment by Thomas55555** [comment]
Ah, I see, you edited your comment more since the draft of this review. Changed the general language. Now it works. Thx.

**Comment by astrandb** [comment]
You must change global language in Settings->System->General and restart HA. Then the swedish entity names  will appear.

**Comment by Thomas55555** [comment]
Thx @astrandb

**Comment by priiduonu** [comment]
Could it be possible to make the translation follow the user setting of the language, not the general setting?

**Comment by astrandb** [comment]
Translation of entity names follow the global setting and translation of states follow the setting int he user profile. This behavior is built into Home Assistant and cannot be changed in integrations.

**Comment by priiduonu** [comment]
Thank you @astrandb for explanation!

**Pull request merged**
