### PR TITLE
Add Camera Entity

### PR DESCRIPTION
**Pull request by prairiesnpr**
This adds a camera entity to plot the GPS location and track of the mower on a user provided image

camera_aeinarr

### CODE REVIEW

**Review by Thomas55555 — CHANGES_REQUESTED** [review]
There is no description of the options. Can you add them in them?
DeepinBildschirmfoto_Bereich auswählen_20220613140826
DeepinBildschirmfoto_Bereich auswählen_20220613140808

**Review by Thomas55555 — CHANGES_REQUESTED** [review]
If the camera is not configured, then the entity is enabled anyway. Can you disable the entity by default, until it's configured?

**Comment by prairiesnpr** [comment]
> There is no description of the options. Can you add them in them? DeepinBildschirmfoto_Bereich auswählen_20220613140826 DeepinBildschirmfoto_Bereich auswählen_20220613140808

Of course, I don't know why I didn't push the updated translations, will get them added this evening

**Review by prairiesnpr — COMMENTED** [review]
Requested changes made

**Comment by Thomas55555** [comment]
Hi, there are still some thing with turning on and turning of the camera which I've marked. I think this is not changed yet. Can you have a look on it? Because I don't think it's possible to turn the camera on and off.

**Comment by prairiesnpr** [comment]
> Hi, there are still some thing with turning on and turning of the camera which I've marked. I think this is not changed yet. Can you have a look on it? Because I don't think it's possible to turn the camera on and off.

I'm sorry, I'm not seeing any comments when I looked at the changes requested.  If you are referencing the functions turn_off and turn_on in camera.py, those would be called by the service camera.turn_on or camera.turn_off (https://www.home-assistant.io/integrations/camera/#service-turn_off).  The idea is that it would save system resources if you didn't want to update the position of the mower.

**Comment by Thomas55555** [comment]
Ah okay, now i got it.

**Comment by dawiinci** [comment]
How do I configure this? 

More specifically: How do I get the path in the image?

**Pull request merged**
